# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 092d1214dcfa625a97d1a5e9ff6ceec3d13c0c3bc5d073d82dfa3b29efff056d1b81432e690c7a2d631a4658b4708d820ea38b8c1800a5c43a7db17bb9d91ab2

test:
  secret_key_base: 6fe7d79cb5f311c70bb8e228c703617fd9d1c167da3e515115df402a2326ea62a24c34f1069d57894be5272030192010c0b3249e2208e475e452eae81c9cbfdf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
